
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-api-marker
  namespace: projet-extraction-tableaux
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout:    "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout:    "600"
spec:
  rules:
    - host: extraction-tableau-marker.lab.sspcloud.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-marker
                port:
                  number: 80
